/**
 * Created by rs on 13/11/16.
 */


const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
const AUTH_USER_FAIL = 'NO_AUTH_USER';
const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAIL = 'LOGOUT_FAIL';
export {
	AUTH_USER_REQUEST,
	AUTHENTICATED_SUCCESS,
	AUTH_USER_FAIL,
	LOGOUT_REQUEST,
	LOGOUT_SUCCESS,
	LOGOUT_FAIL
}
