/**
 * Created by rs on 13/11/16.
 */


const USER_ADD_REQUEST = 'USER_ADD_REQUEST';
const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
const USER_ADD_FAIL = 'USER_ADD_FAIL';

const SIMILAR_TO_GET_REQUEST = 'USER_GET_SIMILAR_TO_REQUEST';
const SIMILAR_TO_GET_SUCCESS = 'USER_GET_SIMILAR_TO_SUCCESS';
const SIMILAR_TO_GET_FAIL = 'USER_GET_SIMILAR_TO_FAIL';

const GET_UNAPPROVED_USERS_REQ = 'GET_UNAPPROVED_USERS_REQ';
const GET_UNAPPROVED_USERS_SUCCESS = 'GET_UNAPPROVED_USERS_SUCCESS'
const GET_UNAPPROVED_USERS_FAIL = 'GET_UNAPPROVED_USERS_FAIL';


const GET_MAPPABLE_MEMBERS_REQ = 'GET_MAPPABLE_MEMBERS_REQ';
const GET_MAPPABLE_MEMBERS_SUCCESS = 'GET_MAPPABLE_MEMBERS_SUCCESS';
const GET_MAPPABLE_MEMBERS_FAIL = 'GET_MAPPABLE_MEMBERS_FAIL';

const APPROVE_MEMBER_REQ = 'APPROVE_MEMBER_REQ';
const APPROVE_MEMBER_SUCCESS = 'APPROVE_MEMBER_SUCCESS';
const APPROVE_MEMBER_FAIL = 'APPROVE_MEMBER_FAIL';

const LIKE_MAPPABLE_USERS_REQ = 'LIKE_MAPPABLE_USERS_REQ';
const LIKE_MAPPABLE_USERS_SUCCESS = 'LIKE_MAPPABLE_USERS_SUCCESS';
const LIKE_MAPPABLE_USERS_FAIL = 'LIKE_MAPPABLE_USERS_FAIL';

export {
	USER_ADD_FAIL,
	USER_ADD_REQUEST,
	USER_ADD_SUCCESS,
	SIMILAR_TO_GET_FAIL,
	SIMILAR_TO_GET_REQUEST,
	SIMILAR_TO_GET_SUCCESS,
	GET_UNAPPROVED_USERS_FAIL,
	GET_UNAPPROVED_USERS_REQ,
	GET_UNAPPROVED_USERS_SUCCESS,
	GET_MAPPABLE_MEMBERS_FAIL,
	GET_MAPPABLE_MEMBERS_REQ,
	GET_MAPPABLE_MEMBERS_SUCCESS,

	APPROVE_MEMBER_FAIL,
	APPROVE_MEMBER_REQ,
	APPROVE_MEMBER_SUCCESS,

	LIKE_MAPPABLE_USERS_FAIL,
	LIKE_MAPPABLE_USERS_REQ,
	LIKE_MAPPABLE_USERS_SUCCESS
}